rm ../bases-work/aa/aa.tgz; tar cvfzp ../bases-work/aa/aa.tgz ../bases-work/aa/aa.*; ./ReparaPIDcitacao.sh aa
rm ../bases-work/abb/abb.tgz; tar cvfzp ../bases-work/abb/abb.tgz ../bases-work/abb/abb.*; ./ReparaPIDcitacao.sh abb
rm ../bases-work/abc/abc.tgz; tar cvfzp ../bases-work/abc/abc.tgz ../bases-work/abc/abc.*; ./ReparaPIDcitacao.sh abc
rm ../bases-work/abem/abem.tgz; tar cvfzp ../bases-work/abem/abem.tgz ../bases-work/abem/abem.*; ./ReparaPIDcitacao.sh abem
rm ../bases-work/abo/abo.tgz; tar cvfzp ../bases-work/abo/abo.tgz ../bases-work/abo/abo.*; ./ReparaPIDcitacao.sh abo
rm ../bases-work/acb/acb.tgz; tar cvfzp ../bases-work/acb/acb.tgz ../bases-work/acb/acb.*; ./ReparaPIDcitacao.sh acb
rm ../bases-work/ag/ag.tgz; tar cvfzp ../bases-work/ag/ag.tgz ../bases-work/ag/ag.*; ./ReparaPIDcitacao.sh ag
rm ../bases-work/anp/anp.tgz; tar cvfzp ../bases-work/anp/anp.tgz ../bases-work/anp/anp.*; ./ReparaPIDcitacao.sh anp
rm ../bases-work/aob/aob.tgz; tar cvfzp ../bases-work/aob/aob.tgz ../bases-work/aob/aob.*; ./ReparaPIDcitacao.sh aob
rm ../bases-work/babt/babt.tgz; tar cvfzp ../bases-work/babt/babt.tgz ../bases-work/babt/babt.*; ./ReparaPIDcitacao.sh babt
rm ../bases-work/bjb/bjb.tgz; tar cvfzp ../bases-work/bjb/bjb.tgz ../bases-work/bjb/bjb.*; ./ReparaPIDcitacao.sh bjb
rm ../bases-work/bjm/bjm.tgz; tar cvfzp ../bases-work/bjm/bjm.tgz ../bases-work/bjm/bjm.*; ./ReparaPIDcitacao.sh bjm
rm ../bases-work/bjmbr/bjmbr.tgz; tar cvfzp ../bases-work/bjmbr/bjmbr.tgz ../bases-work/bjmbr/bjmbr.*; ./ReparaPIDcitacao.sh bjmbr
rm ../bases-work/bjp/bjp.tgz; tar cvfzp ../bases-work/bjp/bjp.tgz ../bases-work/bjp/bjp.*; ./ReparaPIDcitacao.sh bjp
rm ../bases-work/bor/bor.tgz; tar cvfzp ../bases-work/bor/bor.tgz ../bases-work/bor/bor.*; ./ReparaPIDcitacao.sh bor
rm ../bases-work/brag/brag.tgz; tar cvfzp ../bases-work/brag/brag.tgz ../bases-work/brag/brag.*; ./ReparaPIDcitacao.sh brag
rm ../bases-work/ci/ci.tgz; tar cvfzp ../bases-work/ci/ci.tgz ../bases-work/ci/ci.*; ./ReparaPIDcitacao.sh ci
rm ../bases-work/cp/cp.tgz; tar cvfzp ../bases-work/cp/cp.tgz ../bases-work/cp/cp.*; ./ReparaPIDcitacao.sh cp
rm ../bases-work/csp/csp.tgz; tar cvfzp ../bases-work/csp/csp.tgz ../bases-work/csp/csp.*; ./ReparaPIDcitacao.sh csp
rm ../bases-work/cta/cta.tgz; tar cvfzp ../bases-work/cta/cta.tgz ../bases-work/cta/cta.*; ./ReparaPIDcitacao.sh cta
rm ../bases-work/dados/dados.tgz; tar cvfzp ../bases-work/dados/dados.tgz ../bases-work/dados/dados.*; ./ReparaPIDcitacao.sh dados
rm ../bases-work/delta/delta.tgz; tar cvfzp ../bases-work/delta/delta.tgz ../bases-work/delta/delta.*; ./ReparaPIDcitacao.sh delta
rm ../bases-work/dpress/dpress.tgz; tar cvfzp ../bases-work/dpress/dpress.tgz ../bases-work/dpress/dpress.*; ./ReparaPIDcitacao.sh dpress
rm ../bases-work/ea/ea.tgz; tar cvfzp ../bases-work/ea/ea.tgz ../bases-work/ea/ea.*; ./ReparaPIDcitacao.sh ea
rm ../bases-work/ecoa/ecoa.tgz; tar cvfzp ../bases-work/ecoa/ecoa.tgz ../bases-work/ecoa/ecoa.*; ./ReparaPIDcitacao.sh ecoa
rm ../bases-work/ensaio/ensaio.tgz; tar cvfzp ../bases-work/ensaio/ensaio.tgz ../bases-work/ensaio/ensaio.*; ./ReparaPIDcitacao.sh ensaio
rm ../bases-work/ep/ep.tgz; tar cvfzp ../bases-work/ep/ep.tgz ../bases-work/ep/ep.*; ./ReparaPIDcitacao.sh ep
rm ../bases-work/epsic/epsic.tgz; tar cvfzp ../bases-work/epsic/epsic.tgz ../bases-work/epsic/epsic.*; ./ReparaPIDcitacao.sh epsic
rm ../bases-work/eq/eq.tgz; tar cvfzp ../bases-work/eq/eq.tgz ../bases-work/eq/eq.*; ./ReparaPIDcitacao.sh eq
rm ../bases-work/esa/esa.tgz; tar cvfzp ../bases-work/esa/esa.tgz ../bases-work/esa/esa.*; ./ReparaPIDcitacao.sh esa
rm ../bases-work/gmb/gmb.tgz; tar cvfzp ../bases-work/gmb/gmb.tgz ../bases-work/gmb/gmb.*; ./ReparaPIDcitacao.sh gmb
rm ../bases-work/gp/gp.tgz; tar cvfzp ../bases-work/gp/gp.tgz ../bases-work/gp/gp.*; ./ReparaPIDcitacao.sh gp
rm ../bases-work/hb/hb.tgz; tar cvfzp ../bases-work/hb/hb.tgz ../bases-work/hb/hb.*; ./ReparaPIDcitacao.sh hb
rm ../bases-work/hcsm/hcsm.tgz; tar cvfzp ../bases-work/hcsm/hcsm.tgz ../bases-work/hcsm/hcsm.*; ./ReparaPIDcitacao.sh hcsm
rm ../bases-work/his/his.tgz; tar cvfzp ../bases-work/his/his.tgz ../bases-work/his/his.*; ./ReparaPIDcitacao.sh his
rm ../bases-work/ibju/ibju.tgz; tar cvfzp ../bases-work/ibju/ibju.tgz ../bases-work/ibju/ibju.*; ./ReparaPIDcitacao.sh ibju
rm ../bases-work/icse/icse.tgz; tar cvfzp ../bases-work/icse/icse.tgz ../bases-work/icse/icse.*; ./ReparaPIDcitacao.sh icse
rm ../bases-work/jaos/jaos.tgz; tar cvfzp ../bases-work/jaos/jaos.tgz ../bases-work/jaos/jaos.*; ./ReparaPIDcitacao.sh jaos
rm ../bases-work/jbchs/jbchs.tgz; tar cvfzp ../bases-work/jbchs/jbchs.tgz ../bases-work/jbchs/jbchs.*; ./ReparaPIDcitacao.sh jbchs
rm ../bases-work/jbpml/jbpml.tgz; tar cvfzp ../bases-work/jbpml/jbpml.tgz ../bases-work/jbpml/jbpml.*; ./ReparaPIDcitacao.sh jbpml
rm ../bases-work/jped/jped.tgz; tar cvfzp ../bases-work/jped/jped.tgz ../bases-work/jped/jped.*; ./ReparaPIDcitacao.sh jped
rm ../bases-work/mana/mana.tgz; tar cvfzp ../bases-work/mana/mana.tgz ../bases-work/mana/mana.*; ./ReparaPIDcitacao.sh mana
rm ../bases-work/mioc/mioc.tgz; tar cvfzp ../bases-work/mioc/mioc.tgz ../bases-work/mioc/mioc.*; ./ReparaPIDcitacao.sh mioc
rm ../bases-work/mr/mr.tgz; tar cvfzp ../bases-work/mr/mr.tgz ../bases-work/mr/mr.*; ./ReparaPIDcitacao.sh mr
rm ../bases-work/pab/pab.tgz; tar cvfzp ../bases-work/pab/pab.tgz ../bases-work/pab/pab.*; ./ReparaPIDcitacao.sh pab
rm ../bases-work/pd/pd.tgz; tar cvfzp ../bases-work/pd/pd.tgz ../bases-work/pd/pd.*; ./ReparaPIDcitacao.sh pd
rm ../bases-work/pe/pe.tgz; tar cvfzp ../bases-work/pe/pe.tgz ../bases-work/pe/pe.*; ./ReparaPIDcitacao.sh pe
rm ../bases-work/pope/pope.tgz; tar cvfzp ../bases-work/pope/pope.tgz ../bases-work/pope/pope.*; ./ReparaPIDcitacao.sh pope
rm ../bases-work/prc/prc.tgz; tar cvfzp ../bases-work/prc/prc.tgz ../bases-work/prc/prc.*; ./ReparaPIDcitacao.sh prc
rm ../bases-work/ptp/ptp.tgz; tar cvfzp ../bases-work/ptp/ptp.tgz ../bases-work/ptp/ptp.*; ./ReparaPIDcitacao.sh ptp
rm ../bases-work/pvb/pvb.tgz; tar cvfzp ../bases-work/pvb/pvb.tgz ../bases-work/pvb/pvb.*; ./ReparaPIDcitacao.sh pvb
rm ../bases-work/raeel/raeel.tgz; tar cvfzp ../bases-work/raeel/raeel.tgz ../bases-work/raeel/raeel.*; ./ReparaPIDcitacao.sh raeel
rm ../bases-work/ramb/ramb.tgz; tar cvfzp ../bases-work/ramb/ramb.tgz ../bases-work/ramb/ramb.*; ./ReparaPIDcitacao.sh ramb
rm ../bases-work/rarv/rarv.tgz; tar cvfzp ../bases-work/rarv/rarv.tgz ../bases-work/rarv/rarv.*; ./ReparaPIDcitacao.sh rarv
rm ../bases-work/rba/rba.tgz; tar cvfzp ../bases-work/rba/rba.tgz ../bases-work/rba/rba.*; ./ReparaPIDcitacao.sh rba
rm ../bases-work/rbcs/rbcs.tgz; tar cvfzp ../bases-work/rbcs/rbcs.tgz ../bases-work/rbcs/rbcs.*; ./ReparaPIDcitacao.sh rbcs
rm ../bases-work/rbcsoc/rbcsoc.tgz; tar cvfzp ../bases-work/rbcsoc/rbcsoc.tgz ../bases-work/rbcsoc/rbcsoc.*; ./ReparaPIDcitacao.sh rbcsoc
rm ../bases-work/rbedu/rbedu.tgz; tar cvfzp ../bases-work/rbedu/rbedu.tgz ../bases-work/rbedu/rbedu.*; ./ReparaPIDcitacao.sh rbedu
rm ../bases-work/rbent/rbent.tgz; tar cvfzp ../bases-work/rbent/rbent.tgz ../bases-work/rbent/rbent.*; ./ReparaPIDcitacao.sh rbent
rm ../bases-work/rbepid/rbepid.tgz; tar cvfzp ../bases-work/rbepid/rbepid.tgz ../bases-work/rbepid/rbepid.*; ./ReparaPIDcitacao.sh rbepid
rm ../bases-work/rbf/rbf.tgz; tar cvfzp ../bases-work/rbf/rbf.tgz ../bases-work/rbf/rbf.*; ./ReparaPIDcitacao.sh rbf
rm ../bases-work/rbgo/rbgo.tgz; tar cvfzp ../bases-work/rbgo/rbgo.tgz ../bases-work/rbgo/rbgo.*; ./ReparaPIDcitacao.sh rbgo
rm ../bases-work/rbme/rbme.tgz; tar cvfzp ../bases-work/rbme/rbme.tgz ../bases-work/rbme/rbme.*; ./ReparaPIDcitacao.sh rbme
rm ../bases-work/rboto/rboto.tgz; tar cvfzp ../bases-work/rboto/rboto.tgz ../bases-work/rboto/rboto.*; ./ReparaPIDcitacao.sh rboto
rm ../bases-work/rbr/rbr.tgz; tar cvfzp ../bases-work/rbr/rbr.tgz ../bases-work/rbr/rbr.*; ./ReparaPIDcitacao.sh rbr
rm ../bases-work/rbs/rbs.tgz; tar cvfzp ../bases-work/rbs/rbs.tgz ../bases-work/rbs/rbs.*; ./ReparaPIDcitacao.sh rbs
rm ../bases-work/rbsmi/rbsmi.tgz; tar cvfzp ../bases-work/rbsmi/rbsmi.tgz ../bases-work/rbsmi/rbsmi.*; ./ReparaPIDcitacao.sh rbsmi
rm ../bases-work/rbz/rbz.tgz; tar cvfzp ../bases-work/rbz/rbz.tgz ../bases-work/rbz/rbz.*; ./ReparaPIDcitacao.sh rbz
rm ../bases-work/rcbc/rcbc.tgz; tar cvfzp ../bases-work/rcbc/rcbc.tgz ../bases-work/rcbc/rcbc.*; ./ReparaPIDcitacao.sh rcbc
rm ../bases-work/resr/resr.tgz; tar cvfzp ../bases-work/resr/resr.tgz ../bases-work/resr/resr.*; ./ReparaPIDcitacao.sh resr
rm ../bases-work/rlae/rlae.tgz; tar cvfzp ../bases-work/rlae/rlae.tgz ../bases-work/rlae/rlae.*; ./ReparaPIDcitacao.sh rlae
rm ../bases-work/rn/rn.tgz; tar cvfzp ../bases-work/rn/rn.tgz ../bases-work/rn/rn.*; ./ReparaPIDcitacao.sh rn
rm ../bases-work/rpc/rpc.tgz; tar cvfzp ../bases-work/rpc/rpc.tgz ../bases-work/rpc/rpc.*; ./ReparaPIDcitacao.sh rpc
rm ../bases-work/rprs/rprs.tgz; tar cvfzp ../bases-work/rprs/rprs.tgz ../bases-work/rprs/rprs.*; ./ReparaPIDcitacao.sh rprs
rm ../bases-work/rsbmt/rsbmt.tgz; tar cvfzp ../bases-work/rsbmt/rsbmt.tgz ../bases-work/rsbmt/rsbmt.*; ./ReparaPIDcitacao.sh rsbmt
rm ../bases-work/rsp/rsp.tgz; tar cvfzp ../bases-work/rsp/rsp.tgz ../bases-work/rsp/rsp.*; ./ReparaPIDcitacao.sh rsp
rm ../bases-work/sa/sa.tgz; tar cvfzp ../bases-work/sa/sa.tgz ../bases-work/sa/sa.*; ./ReparaPIDcitacao.sh sa
rm ../bases-work/soc/soc.tgz; tar cvfzp ../bases-work/soc/soc.tgz ../bases-work/soc/soc.*; ./ReparaPIDcitacao.sh soc
rm ../bases-work/spmj/spmj.tgz; tar cvfzp ../bases-work/spmj/spmj.tgz ../bases-work/spmj/spmj.*; ./ReparaPIDcitacao.sh spmj
