./ReparaPIDcitacao.sh aa
./ReparaPIDcitacao.sh abb
./ReparaPIDcitacao.sh abc
./ReparaPIDcitacao.sh abem
./ReparaPIDcitacao.sh abo
./ReparaPIDcitacao.sh acb
./ReparaPIDcitacao.sh ag
./ReparaPIDcitacao.sh anp
./ReparaPIDcitacao.sh aob
./ReparaPIDcitacao.sh babt
./ReparaPIDcitacao.sh bjb
./ReparaPIDcitacao.sh bjm
./ReparaPIDcitacao.sh bjmbr
./ReparaPIDcitacao.sh bjp
./ReparaPIDcitacao.sh bor
./ReparaPIDcitacao.sh brag
./ReparaPIDcitacao.sh ci
./ReparaPIDcitacao.sh cp
./ReparaPIDcitacao.sh csp
./ReparaPIDcitacao.sh cta
./ReparaPIDcitacao.sh dados
./ReparaPIDcitacao.sh delta
./ReparaPIDcitacao.sh dpress
./ReparaPIDcitacao.sh ea
./ReparaPIDcitacao.sh ecoa
./ReparaPIDcitacao.sh ensaio
./ReparaPIDcitacao.sh ep
./ReparaPIDcitacao.sh epsic
./ReparaPIDcitacao.sh eq
./ReparaPIDcitacao.sh esa
./ReparaPIDcitacao.sh gmb
./ReparaPIDcitacao.sh gp
./ReparaPIDcitacao.sh hb
./ReparaPIDcitacao.sh hcsm
./ReparaPIDcitacao.sh his
./ReparaPIDcitacao.sh ibju
./ReparaPIDcitacao.sh icse
./ReparaPIDcitacao.sh jaos
./ReparaPIDcitacao.sh jbchs
./ReparaPIDcitacao.sh jbpml
./ReparaPIDcitacao.sh jped
./ReparaPIDcitacao.sh mana
./ReparaPIDcitacao.sh mioc
./ReparaPIDcitacao.sh mr
./ReparaPIDcitacao.sh pab
./ReparaPIDcitacao.sh pd
./ReparaPIDcitacao.sh pe
./ReparaPIDcitacao.sh pope
./ReparaPIDcitacao.sh prc
./ReparaPIDcitacao.sh ptp
./ReparaPIDcitacao.sh pvb
./ReparaPIDcitacao.sh raeel
./ReparaPIDcitacao.sh ramb
./ReparaPIDcitacao.sh rarv
./ReparaPIDcitacao.sh rba
./ReparaPIDcitacao.sh rbcs
./ReparaPIDcitacao.sh rbcsoc
./ReparaPIDcitacao.sh rbedu
./ReparaPIDcitacao.sh rbent
./ReparaPIDcitacao.sh rbepid
./ReparaPIDcitacao.sh rbf
./ReparaPIDcitacao.sh rbgo
./ReparaPIDcitacao.sh rbme
./ReparaPIDcitacao.sh rboto
./ReparaPIDcitacao.sh rbr
./ReparaPIDcitacao.sh rbs
./ReparaPIDcitacao.sh rbsmi
./ReparaPIDcitacao.sh rbz
./ReparaPIDcitacao.sh rcbc
./ReparaPIDcitacao.sh resr
./ReparaPIDcitacao.sh rlae
./ReparaPIDcitacao.sh rn
./ReparaPIDcitacao.sh rpc
./ReparaPIDcitacao.sh rprs
./ReparaPIDcitacao.sh rsbmt
./ReparaPIDcitacao.sh rsp
./ReparaPIDcitacao.sh sa
./ReparaPIDcitacao.sh soc
./ReparaPIDcitacao.sh spmj
