# Declaracao de parametros conforme Formulario de Informacoes
# -----------------------------------------------------------

export SIGLA2=??
export SIGLA3=???
export PATH_BASES_HOMOLOG=/home/???/www/bases
export TESTE=scielo3
export HOMOL=scielohm1

# Informacoes para processamento de links
  # Se tudo estiver na rede da BIREME usar IN_BIREME=TRUE
export     IN_BIR=TRUE
export      SLINK="serverofi2"
export   FTPLOGIN="user cdrom cdr,./"
export PATH_LINKS="/bases/lnk.000"
